### ISSUE TITLE
Install instructions don't work if you have PsGet

### ISSUE THREAD

**Issue by timabell** [qbikez/ps-csproj#13]
Annoyingly [PsGet](http://psget.net/) overwrites powershell's built-in `Install-Module` - http://superuser.com/a/996448/8271

So you get

```
C:\repos> install-module csproj
Module csproj was not found in central repository
At C:\Users\Administrator\Documents\WindowsPowerShell\Modules\PsGet\PsGet.psm1:694 char:13
+             throw "Module $Module was not found in central repository ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Module csproj w...tral repository:String) [], RuntimeException
    + FullyQualifiedErrorId : Module csproj was not found in central repository
```

followed by some head-scratching.

Suggestions:

* publish to PsGet gallery as well?
* update instructions with gotcha?
* make psget read the main gallery...

**Comment by timabell** [comment]
workaround: http://superuser.com/a/1181259/8271

    C:\repos> powershellget\install-module csproj

**Comment by qbikez** [comment]
I updated instructions and prefixed `install-module` with `PowerShellGet`, as you suggested.

**Comment by timabell** [comment]
Super! Thanks.
